"""add_summary_external_id_language_to_content_items

Revision ID: d1bbec0dcfae
Revises: dfe6a65ca915
Create Date: 2026-09-07 12:00:52.344679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1bbec0dcfae'
down_revision: Union[str, None] = 'dfe6a65ca915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_items', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('content_items', sa.Column('external_id', sa.String(length=512), nullable=True))
    op.add_column('content_items', sa.Column('language', sa.String(length=10), server_default='en', nullable=True))
    op.create_index(op.f('ix_content_items_external_id'), 'content_items', ['external_id'], unique=False)
    op.create_index('ix_content_items_source_external', 'content_items', ['source_id', 'external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_content_items_source_external', table_name='content_items')
    op.drop_index(op.f('ix_content_items_external_id'), table_name='content_items')
    op.drop_column('content_items', 'language')
    op.drop_column('content_items', 'external_id')
    op.drop_column('content_items', 'summary')
    # ### end Alembic commands ###
