"""create_initial_models

Revision ID: 9d54944eede9
Revises: 
Create Date: 2026-09-07 07:41:02.377950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d54944eede9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('fetch_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_enabled'), 'sources', ['enabled'], unique=False)
    op.create_index(op.f('ix_sources_slug'), 'sources', ['slug'], unique=True)
    op.create_index(op.f('ix_sources_type'), 'sources', ['type'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('headline', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_takeaway', sa.Text(), nullable=True),
    sa.Column('why_it_matters', sa.Text(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_curated', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_category'), 'stories', ['category'], unique=False)
    op.create_index('ix_stories_curated_importance', 'stories', ['is_curated', 'importance_score'], unique=False)
    op.create_index(op.f('ix_stories_importance_score'), 'stories', ['importance_score'], unique=False)
    op.create_index(op.f('ix_stories_is_curated'), 'stories', ['is_curated'], unique=False)
    op.create_index(op.f('ix_stories_published_at'), 'stories', ['published_at'], unique=False)
    op.create_table('content_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=True),
    sa.Column('canonical_url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('processing_state', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_items_canonical_url'), 'content_items', ['canonical_url'], unique=True)
    op.create_index(op.f('ix_content_items_content_hash'), 'content_items', ['content_hash'], unique=False)
    op.create_index(op.f('ix_content_items_processing_state'), 'content_items', ['processing_state'], unique=False)
    op.create_index(op.f('ix_content_items_published_at'), 'content_items', ['published_at'], unique=False)
    op.create_index(op.f('ix_content_items_source_id'), 'content_items', ['source_id'], unique=False)
    op.create_index('ix_content_items_source_published', 'content_items', ['source_id', 'published_at'], unique=False)
    op.create_index(op.f('ix_content_items_story_id'), 'content_items', ['story_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_items_story_id'), table_name='content_items')
    op.drop_index('ix_content_items_source_published', table_name='content_items')
    op.drop_index(op.f('ix_content_items_source_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_published_at'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_processing_state'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_content_hash'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_canonical_url'), table_name='content_items')
    op.drop_table('content_items')
    op.drop_index(op.f('ix_stories_published_at'), table_name='stories')
    op.drop_index(op.f('ix_stories_is_curated'), table_name='stories')
    op.drop_index(op.f('ix_stories_importance_score'), table_name='stories')
    op.drop_index('ix_stories_curated_importance', table_name='stories')
    op.drop_index(op.f('ix_stories_category'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_sources_type'), table_name='sources')
    op.drop_index(op.f('ix_sources_slug'), table_name='sources')
    op.drop_index(op.f('ix_sources_enabled'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
