from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import UUID, uuid4
from pydantic import BaseModel, ConfigDict, Field


class ContentType(str, Enum):
    """Canonical classification for ingested content items."""

    ARTICLE = "ARTICLE"
    RESEARCH_PAPER = "RESEARCH_PAPER"
    VIDEO = "VIDEO"
    COMMUNITY_POST = "COMMUNITY_POST"


class ProcessingStatus(str, Enum):
    """Lifecycle states for AI intelligence processing."""

    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class AIAnalysisResult(BaseModel):
    """Structured intelligence payload generated by AI providers."""

    summary: str = Field(description="Concise, factual summary of the content.")
    key_points: List[str] = Field(default_factory=list, description="Extracted key factual points.")
    topics: List[str] = Field(default_factory=list, description="Categorized AI/ML topics.")
    relevance_score: float = Field(ge=0.0, le=1.0, description="Normalized relevance score from 0.0 to 1.0.")
    model_name: str = Field(default="unknown", description="Model identifier used for analysis.")


class ContentItemDomain(BaseModel):
    """Domain representation of an ingested content piece preserving source provenance and AI intelligence."""

    id: UUID = Field(default_factory=uuid4)
    source_id: UUID
    story_id: Optional[UUID] = None
    canonical_url: str
    title: str
    summary: Optional[str] = None
    raw_content: Optional[str] = None
    author: Optional[str] = None
    published_at: datetime
    fetched_at: datetime
    external_id: Optional[str] = None
    language: Optional[str] = "en"
    content_hash: str
    processing_state: str = "PENDING"
    content_type: ContentType = ContentType.ARTICLE
    thumbnail_url: Optional[str] = None
    metadata_json: Dict[str, Any] = Field(default_factory=dict)

    # AI Processed Intelligence
    ai_summary: Optional[str] = None
    ai_key_points: Optional[List[str]] = None
    ai_topics: Optional[List[str]] = None
    ai_relevance_score: Optional[float] = None
    ai_model: Optional[str] = None
    ai_processed_at: Optional[datetime] = None
    embedding: Optional[List[float]] = None
    embedding_model: Optional[str] = None

    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    model_config = ConfigDict(from_attributes=True)
